version: '3'
services:
  codeceptjs:
    image: codeception/codeceptjs
    depends_on:
      - chrome
      - firefox
      - web
    volumes:
      - .:/tests
  web:
    image: node
    command: node app/server.js
    volumes:
      - .:/app
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - GRID_MAX_SESSION=5
      - GRID_MAX_INSTANCES=5      
  chrome:
    image: selenium/node-chrome-debug
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
      - NODE_MAX_SESSION=5
      - NODE_MAX_INSTANCES=5
    ports:
        - 5900:5900
  firefox:
    image: selenium/node-firefox-debug
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
      - NODE_MAX_SESSION=5
      - NODE_MAX_INSTANCES=5
    ports:
        - 5901:5900