npm install jasmine
npm install jasmine-node 
npm install jsonschema 
npm install content-type
npm install jest
npm install jest-cli
npm install request
npm install frisby@2.0.5 
npm install body-parser
